name: rspchitwan-staging

services:
  app:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
      args:
        DB_PROVIDER: ${DB_PROVIDER:-mysql}
    image: rspchitwan-staging
    container_name: rspchitwan_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "5005:3000"
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - shared_network

volumes:
  uploads_data:

networks:
  shared_network:
    external: true
    name: ${SHARED_NETWORK_NAME}
